### ISSUE TITLE
Why doesn't the date match the chart?

### ISSUE THREAD

**Issue by SuzGori** [yermolim/ts-gantt#11]
As you can see on the screen, the date of the task does not match the date of the chart.
Do you know the possible reasons?
Can I set something in dayjs to solve this?

Gantt
![image](https://user-images.githubusercontent.com/54024317/128320281-e7436d43-2660-46de-bec7-8a980f4cb1cb.png)

Task
<img width="339" alt="スクリーンショット 2021-08-05 17 47 38" src="https://user-images.githubusercontent.com/54024317/128321121-55b68581-4b06-4b6e-8c64-226dc4a81236.png">

![image](https://user-images.githubusercontent.com/54024317/128321277-91153ef6-b27f-4f1c-951c-fe2b28d0fe28.png)

**Comment by SuzGori** [comment]
@yermolim  
Is there anything I should do?

**Comment by SuzGori** [comment]
It looked like +20 at the x was just right.
What could be causing this?
Is it because I tweaked the size of the table?

Options here
```Typescript
const options = new TsGanttOptions({
        columnsMinWidthPx: [180, 60, 100, 100, 100, 100, 80, 80],
        chartDateOffsetDays: {"day": 7, "week": 10, "month": 240, "year": 730},
        chartDateOffsetDaysMin: {"day": 0, "week": 0, "month": 30, "year": 132},
      });
```

before

```HTML
<svg width="234" height="40" class="tsg-chart-bar-group" x="180"><svg x="0" y="1.5" width="220" height="17" class="tsg-chart-bar-wrapper"><rect x="1" y="1" width="218" height="15" rx="6" ry="6" class="tsg-chart-bar-planned"></rect><rect x="1" y="1" width="65.4" height="15" rx="6" ry="6" class="tsg-chart-bar-planned-progress"></rect></svg></svg>
```


replace
```HTML
<svg width="234" height="40" class="tsg-chart-bar-group" x="200"><svg x="0" y="1.5" width="220" height="17" class="tsg-chart-bar-wrapper"><rect x="1" y="1" width="218" height="15" rx="6" ry="6" class="tsg-chart-bar-planned"></rect><rect x="1" y="1" width="65.4" height="15" rx="6" ry="6" class="tsg-chart-bar-planned-progress"></rect></svg></svg>
```

**Comment by yermolim** [comment]
> Is there anything I should do?

I'm sorry I haven't had much spare time in recent weeks to look at this issue. I'll try to test it this weekend if nothing gets in the way

**Comment by yermolim** [comment]
Fixed calculation of chart bar offsets. Should behave correctly now.

**Comment by SuzGori** [comment]
@yermolim 

Thank you!!!
"test-title" has been improved!!!!

But...
"test-title3" is still misaligned.

Can you tell me what it is?

![image](https://user-images.githubusercontent.com/54024317/130388113-a2123b44-fb96-4417-b7ce-f3bfd01f720c.png)

**Comment by SuzGori** [comment]
It always seems to add a day after the second one.
![image](https://user-images.githubusercontent.com/54024317/130396652-e896ff94-1096-4992-b6ea-2fa5e27d6975.png)

**Comment by yermolim** [comment]
> It always seems to add a day after the second one.

Unfortunately, I'm pretty busy these days, so I can't devote a lot of time to searching for the cause of this problem. I had thought it might be connected with local time zones (because you're using time values while I've designed this module to work with dates only, without testing how it works with local time), but even when I added some boundary values of time (which can cause date change for my time zone if not handled right) to my data I still can't see such problem on my machine. So I can only advise you to try removing time from your data and check if it will work correctly. If the problem persists please let me know.

**Comment by SuzGori** [comment]
Thank you for your time.
I am grateful to be able to comment on this wonderful module.

And I followed your advice and buried Hour onwards to zero and it fixed it.

I am going to close this case.
If there is anything I can do to help, I would appreciate it if you could let me know.

May God continue to bless this module!
