### ISSUE TITLE
Container is null

### ISSUE THREAD

**Issue by SuzGori** [yermolim/ts-gantt#8]
Hi, very nice library!
Here's hoping this gets even better!

I got the following error message.
What does it say?
`Container is null`

I am using Angular.

TS
```typescript
import { Component, VERSION, OnInit } from '@angular/core';
import { TsGantt } from 'ts-gantt';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  name = 'Angular ' + VERSION.major;
  chart = new TsGantt('#gantt-container');

  ngOnInit() {
    this.chart.tasks = [
      {
        id: '1',
        parentId: null,
        name: 'Root1',
        progress: 20,
        datePlannedStart: new Date(),
        datePlannedEnd: new Date(),
        dateActualStart: new Date(),
        dateActualEnd: new Date(),
        localizedNames: { en: 'Root 1', uk: 'Корінь 1', ru: 'Корень 1' }
      }
    ];
  }
}
```

HTML
```html
<div id="gantt-container"></div>
<div class="button-div">
  <button id="btn-locale-en">En</button>
  <button id="btn-locale-uk">Uk</button>
  <button id="btn-locale-ru">Ru</button>
</div>
<div class="button-div">
  <button id="btn-scale-day">Day</button>
  <button id="btn-scale-week">Week</button>
  <button id="btn-scale-month">Month</button>
  <button id="btn-scale-year">Year</button>
</div>
<div class="button-div">
  <button id="btn-bar-both">Both</button>
  <button id="btn-bar-planned">Planned</button>
  <button id="btn-bar-actual">Actual</button>
</div>
<div class="button-div">
  <button id="btn-row-select">Select 1st</button>
</div>
<div class="button-div">
  <button id="btn-all-expand">Expand</button>
  <button id="btn-all-collapse">Collapse</button>
</div>
```

style.css
```css
@import 'ts-gantt/dist/styles.min.css'
```

**Comment by yermolim** [comment]
Hi! Thanks!
I suggest that you're getting such an error message because at the moment when the "chart" field is being initialized, the DOM is not built yet (so ```<div id="gantt-container"></div>``` does not exist when the chart constructor gets called). The problem should go if you move chart creation inside your ```ngOnInit()``` method, like this:
```typescript
chart: TsGantt;

ngOnInit() {
  this.chart = new TsGantt('#gantt-container');
 // rest of code
```
And ```ngAfterViewInit()``` will be actually even more safe bet because it is designed to be called after the component structure is fully initialized.

If that won't help, I'll do some tests when I have a free time.

**Comment by SuzGori** [comment]
Thank you.
It's working.🙌
I'm sorry it was an my Angular code's problem.

By the way, are you going to make a wrapper library or ReadMe for Angular?
I'd like to see if I can contribute something too!

**Comment by yermolim** [comment]
> Thank you.
> It's working

Great!

> By the way, are you going to make a wrapper library or ReadMe for Angular?

I'll do it if I have time.
